import { NextRequest, NextResponse } from "next/server";
import { svc } from "@/lib/supabase/service";
import { sendEmail } from "@/lib/resend";
import { sendSMS } from "@/lib/twilio";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

// Daily watcher for the Twilio A2P 10DLC campaign status.
//
// Polls Twilio every day. Compares the current campaign_status against the
// last value we stored in autonomous_actions (action_type='twilio_a2p_watch').
// Emails admin only when the status changes — idle days produce no noise.
// When the status flips to VERIFIED, also fires a real test SMS via the 901
// number so we know carrier delivery is actually live, not just registered.

const MESSAGING_SERVICE_SID = "MG512a8a255fad04ac05df9a6ff4ee53e9";

interface TwilioCompliance {
  sid: string;
  campaign_status?: string;
  campaign_id?: string | null;
  errors?: Array<{ description?: string; error_code?: number; fields?: string[] }>;
  date_created?: string;
  date_updated?: string;
}

export async function GET(req: NextRequest) {
  const auth = req.headers.get("authorization");
  if (auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const accountSid = process.env.TWILIO_ACCOUNT_SID;
  const authToken = process.env.TWILIO_AUTH_TOKEN;
  if (!accountSid || !authToken) {
    return NextResponse.json({ error: "Twilio creds missing" }, { status: 500 });
  }

  const supabase = svc();
  const { data: org } = await supabase
    .from("organizations")
    .select("id")
    .eq("slug", "maco-transport")
    .single();
  if (!org) return NextResponse.json({ error: "Org not found" }, { status: 500 });

  // Pull current campaign state from Twilio.
  const tRes = await fetch(
    `https://messaging.twilio.com/v1/Services/${MESSAGING_SERVICE_SID}/Compliance/Usa2p`,
    {
      headers: {
        Authorization:
          "Basic " + Buffer.from(`${accountSid}:${authToken}`).toString("base64"),
      },
      cache: "no-store",
    }
  );
  if (!tRes.ok) {
    return NextResponse.json(
      { error: "Twilio API error", status: tRes.status },
      { status: 502 }
    );
  }
  const body = (await tRes.json()) as { compliance?: TwilioCompliance[] };
  const camp = body.compliance?.[0];
  if (!camp) {
    return NextResponse.json({ error: "No A2P campaign found on service" }, { status: 404 });
  }

  const currentStatus = camp.campaign_status ?? "UNKNOWN";

  // What was the previous status we logged?
  const { data: prevRow } = await supabase
    .from("autonomous_actions")
    .select("description, reasoning, executed_at")
    .eq("org_id", org.id)
    .eq("action_type", "twilio_a2p_watch")
    .order("executed_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const prevStatus = parseStatusFromReasoning(prevRow?.reasoning ?? "") ?? "UNKNOWN";
  const changed = prevStatus !== currentStatus;

  const adminEmail =
    process.env.ADMIN_EMAIL ?? "rmassey@macotransport.com";
  const adminPhone = process.env.ADMIN_PHONE ?? null;

  const actionsTaken: string[] = [];

  if (changed) {
    if (currentStatus === "VERIFIED") {
      actionsTaken.push("status->VERIFIED: email admin");
      await sendEmail(
        adminEmail,
        "🎉 Twilio A2P campaign VERIFIED — SMS is live",
        emailVerified(camp)
      );
      // Send a real test SMS to confirm carrier delivery, not just registration.
      if (adminPhone) {
        const smsRes = await sendSMS(
          adminPhone,
          `Maco Transport SMS is now live. This message is auto-generated by DriveIQ to confirm A2P 10DLC carrier delivery is working. Reply STOP to opt out.`
        );
        actionsTaken.push(
          smsRes.success
            ? `sent test SMS to admin (sid ${smsRes.sid})`
            : `test SMS failed: ${smsRes.error}`
        );
      }
    } else if (currentStatus === "FAILED") {
      actionsTaken.push("status->FAILED: email admin + inbox item");
      const errs = camp.errors ?? [];
      await sendEmail(
        adminEmail,
        "⚠️ Twilio A2P campaign rejected — action needed",
        emailFailed(camp, errs)
      );
      await supabase.from("cmo_inbox_items").insert({
        org_id: org.id,
        item_type: "twilio_a2p_failed",
        title: `Twilio A2P campaign rejected (${errs[0]?.error_code ?? "no code"})`,
        action_description:
          errs.map((e) => `[${e.error_code}] ${e.description}`).join(" | ") ||
          "Campaign failed without specific error message.",
        reasoning:
          "TCR rejected the latest A2P 10DLC campaign submission. Until this is approved, no driver SMS will be delivered.",
        priority: "high",
        status: "pending",
        data_points: {
          twilio_sid: camp.sid,
          errors: errs,
          campaign_status: currentStatus,
        } as Record<string, unknown>,
      });
    } else {
      actionsTaken.push(`status->${currentStatus}: status changed (no email)`);
      // Intermediate states (IN_PROGRESS, etc.) — log only.
    }
  }

  // Log this check no matter what.
  await supabase.from("autonomous_actions").insert({
    org_id: org.id,
    action_type: "twilio_a2p_watch",
    description: changed
      ? `Twilio A2P status changed: ${prevStatus} -> ${currentStatus}`
      : `Twilio A2P status unchanged: ${currentStatus}`,
    reasoning: `status=${currentStatus} sid=${camp.sid} campaign_id=${camp.campaign_id ?? "none"}`,
  });

  return NextResponse.json({
    ok: true,
    previous_status: prevStatus,
    current_status: currentStatus,
    changed,
    actions_taken: actionsTaken,
    errors: camp.errors ?? [],
  });
}

function parseStatusFromReasoning(reasoning: string): string | null {
  const m = reasoning.match(/^status=([A-Z_]+)/);
  return m ? m[1] : null;
}

function emailVerified(camp: TwilioCompliance): string {
  return `
    <p>Your Twilio A2P 10DLC campaign just changed to <strong>VERIFIED</strong>.</p>
    <p>SMS to drivers is now live end-to-end. The hourly drip cron will deliver messages from this point forward.</p>
    <p>I just sent a test SMS to your phone (${process.env.ADMIN_PHONE ?? "ADMIN_PHONE unset"}) from the 901 number to confirm carrier delivery is actually working — not just registration. Check your phone.</p>
    <h3>Details</h3>
    <ul>
      <li>SID: ${camp.sid}</li>
      <li>Campaign ID: ${camp.campaign_id ?? "(pending TCR assignment)"}</li>
      <li>Status: ${camp.campaign_status}</li>
    </ul>
  `;
}

function emailFailed(
  camp: TwilioCompliance,
  errors: NonNullable<TwilioCompliance["errors"]>
): string {
  const errList = errors
    .map(
      (e) => `<li><strong>[${e.error_code ?? "?"}]</strong> ${e.description ?? "(no description)"}${e.fields?.length ? ` <em>(fields: ${e.fields.join(", ")})</em>` : ""}</li>`
    )
    .join("");
  return `
    <p>Your Twilio A2P 10DLC campaign was reviewed and <strong>REJECTED</strong>. SMS will continue to fail until this is fixed.</p>
    <h3>Errors</h3>
    <ul>${errList || "<li>(none returned)</li>"}</ul>
    <p>A high-priority item has been added to your <a href="${process.env.NEXT_PUBLIC_APP_URL ?? "https://driveiq-virid.vercel.app"}/dashboard/ai-cmo/inbox">CMO inbox</a> so you can resubmit when you're ready.</p>
    <h3>Details</h3>
    <ul>
      <li>SID: ${camp.sid}</li>
      <li>Status: ${camp.campaign_status}</li>
    </ul>
  `;
}
